### ISSUE TITLE
Wrong velocity type

### ISSUE THREAD

**Issue by bjmcternan** [Team293/InfiniteRecharge#18]
https://github.com/Team293/InfiniteRecharge/blob/64b6f85b65f0e809232599b3ef9a0684c85d7fad/src/main/java/frc/robot/commands/AutonomousCommand.java#L110

m_targetPose.getVelocity() should be **m_drivetrain**.getVelocity()

**Comment by cartha353** [comment]
Issue resolved in AutoNav_Tuning branch

**Comment by bjmcternan** [comment]
Issues can only be closed properly through a PR

**Comment by bjmcternan** [comment]
This has been resolved and tested
