### ISSUE TITLE
Configure NavX to use SPI instead of I2C

### ISSUE THREAD

**Issue by HarrisHamid** [Team293/InfiniteRecharge#32]
https://github.com/Team293/InfiniteRecharge/blob/d72878ea880f8a05a1509f2249a24cafa976f3d3/src/main/java/frc/robot/subsystems/Drivetrain.java#L107

https://docs.wpilib.org/en/stable/docs/yearly-overview/known-issues.html#onboard-i2c-causing-system-lockups

According to the article, there may be lockups using I2C therefore the NavX should be configured to use SPI instead of I2C. 
Should look similar to "ahrs = new AHRS(SPI.Port.kMXP);"

**Comment by bjmcternan** [comment]
Created by accident
